### ISSUE TITLE
License info being included twice after Webpack 4 build

### ISSUE THREAD

**Issue by bruffstar** [webpack-contrib/uglifyjs-webpack-plugin#294] opened 2018-05-16 23:48 UTC
Webpack 4 still uses ``uglifyjs-webpack-plugin`` if ``mode: "production"`` right?

If so... see problem here...

![image](https://user-images.githubusercontent.com/1890098/40149242-f69829dc-5972-11e8-8ffd-026f01afde86.png)

Not sure if this is a Webpack/uglifyjs issue or an issue with the [package](https://github.com/JedWatson/classnames) that has the duplicate license info showing. (I have also [opened an issue](https://github.com/JedWatson/classnames/issues/163) with them to investigate).

In the bundled file, no other third party scripts are adding the license info twice.

I thought it was maybe because the "classnames" package has license info in ``index.js``, ``bind.js`` & ``dedupe.js``. However, I ruled this out after adding a test change in the copyright text in only ``index.js`` and the change was showing on both license comments in the bundle.

**Webpack:** v4.8.3
**NPM:** v5.6.0
**Node:** v8.1.1

###### webpack.config.js
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    mode: 'production',
    devtool: "source-maps",
    entry: "./src/js/index.tsx",
    output: {
        path: __dirname + "/dist",
        filename: "js/bundle.min.js"
    },
    resolve: {
        extensions: [".ts", ".tsx", ".js", ".json"]
    },
    module: {
        rules: [
            {
                test: /\.(ts|tsx)$/,
                use: [
                    {
                        loader: 'ts-loader'
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    use: [{
                        loader: 'css-loader',
                    }, {
                        loader: 'sass-loader'
                    }],
                    fallback: 'style-loader'
                })
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/bundle.min.css',
            allChunks: true,
        })
    ],
    externals: {
        "react": "React",
        "react-dom": "ReactDOM"
    },
};
```

**Comment by bruffstar** [comment] 2018-05-17 00:17
I have made a super simple example here: https://github.com/bruffstar/bug-test

See ``dist/index.js`` for an exmaple output with the duplicate license comment.

**Comment by evilebottnawi** [comment] 2018-05-17 10:31
@bruffstar thanks i will looks what is wrong and what we can do with duplicate licenses

**Comment by tsangint** [comment] 2018-09-03 01:47
Did this resolved？

**Comment by evilebottnawi** [comment] 2018-09-03 09:42
@tsangint no problem in `uglify-es`

**Comment by stevenvachon** [comment] 2018-10-18 17:31
Duplicate of #158

**Comment by evilebottnawi** [comment] 2018-10-18 17:33
@stevenvachon not quite, it will be bug in `uglify-es`

**Closed by evilebottnawi** 2018-10-18 17:33 UTC
Labels: priority: 5 (nice to have), semver: Patch, severity: 4 (inconvenient), type: Bug
