### ISSUE TITLE
Couldn't parse bundle asset "vendors~typeahead.chunk.min.js". Analyzer will use module sizes from stats file.

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/uglifyjs-webpack-plugin#261] opened 2018-03-16 16:33 UTC
Plugin version 1.2.4
webpack 4

This only happens in production when setting ` sourceMap: false`, when set to true, it runs fine!

```
 new UglifyJsPlugin({ 
            sourceMap: false, // <-- using false here, generates the error above
            uglifyOptions: {
                ecma: 5,
                warnings: true
            }
        })
```

**Here the complete Log-file:**
[2018-03-16T16_31_25_817Z-debug.log](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1820016/2018-03-16T16_31_25_817Z-debug.log)

**Comment by evilebottnawi** [comment] 2018-03-16 16:35
@Legends can you provide more detailed log, because log above contain only npm stacktrace

**Comment by Legends** [comment] 2018-03-16 17:20
`npm run prod`

here it is: --> [uglify-sourcemap-false-production.log](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/files/1820194/uglify-sourcemap-false-production.log)

**Comment by evilebottnawi** [comment] 2018-03-16 17:44
@Legends problem in `source-map` package. It is hard debug without source :disappointed: Need reproducible test repo

**Comment by Legends** [comment] 2018-03-16 17:57
Moved the issue to source-maps repo.

**Comment by Legends** [comment] 2018-03-17 01:37
Here is the [repo](https://github.com/Legends/sourceMapsIssueDemo) which replicates the error.

I have opened a new issue [here](https://github.com/mozilla/source-map/issues/328)

**Comment by evilebottnawi** [comment] 2018-03-19 09:00
@Legends I will investigate this in near future :+1:

**Comment by Legends** [comment] 2018-03-19 21:35
I think the issue arises because I have set 
```
module.exports = {
    devtool: 'source-map',
```
but in the UglifyJS-Plugin I set it to false:
```
new UglifyJsPlugin({ 
            sourceMap: false,
```
Perhaps an error message would be nice, that explains the issue or the plugin overrides `devtool` setting by default.
The problem is created in UglifyJS-webpack-plugin:

```
var _asset$sourceAndMap = asset.sourceAndMap(),
                  source = _asset$sourceAndMap.source,
                  map = _asset$sourceAndMap.map;  // <--- returns null

              input = source;
              inputSourceMap = map; // inputSourceMap  is now null

              sourceMap = new _sourceMap.SourceMapConsumer(inputSourceMap); // fails
```

**Comment by Legends** [comment] 2018-03-19 23:51
@pbrain19 has the same error msg, but he uses a different configuration [here](https://github.com/webpack/webpack/issues/1385)

**Comment by Legends** [comment] 2018-03-21 13:30
@evilebottnawi What needs to be done here? Can I help somehow?

**Comment by evilebottnawi** [comment] 2018-03-21 13:32
@Legends no, WIP :+1:

**Comment by evilebottnawi** [comment] 2018-03-26 18:54
@Legends bug, work on PR. Thanks!

**Comment by evilebottnawi** [comment] 2018-03-26 19:39
Fixed in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/268

**Closed** 2018-04-12 14:02 UTC
Labels: flag: Needs more info, priority: 3 (required), semver: Patch, severity: 3 (broken), type: Bug
