### ISSUE TITLE
ERROR TypeError: n._moduleDoBootstrap is not a function

### ISSUE THREAD

**Issue by mrjohnr** [webpack-contrib/uglifyjs-webpack-plugin#160] opened 2017-11-07 16:31 UTC
I'm using uglifyjs-webpack-plugin 1.0.1  in a webpack+angular 4 project.

In webpack.config.js I have this code:

```
const Uglify = require("uglifyjs-webpack-plugin"); 
....
 const sharedConfig = {
..........
,
  plugins: [new CheckerPlugin(),new Uglify()] 
```
after publishing the project I got this error in console,add app not working:

> ERROR TypeError: n._moduleDoBootstrap is not a function

if I remove the Uglify() plugin call,application is working.
 If I only copy the obfuscated main-server.js,app still work,how to fix that.
 thanks

**Comment by evilebottnawi** [comment] 2017-11-08 09:34
@mrjohnr can you create minimum reproducible test repo?

**Comment by dan-lee** [comment] 2017-11-09 09:16
I had the same problem, but unfortunately I cannot provide a reproducible test repo. But I found that `uglify-es` is responsible somehow. I added following to my `package.json` and now it works again:
```
  "resolutions": {
    "uglifyjs-webpack-plugin/uglify-es": "3.1.6"
  }
```
So something between `uglify-es@3.1.6` and `uglify-es@3.1.7` happened which lead to the issue.
Maybe this helps in some way.

**Comment by evilebottnawi** [comment] 2017-11-09 09:22
@mrjohnr solution about help?

**Comment by mrjohnr** [comment] 2017-11-09 11:08
Today I'll do the test
Where do I have to put 'resolutions' I'm thinking to something like that:

```
{
  "name": "Myapp",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
  .................
    "uglifyjs-webpack-plugin": "1.0.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@types/chai": "4.0.1",
.......
    "npm-install-webpack-plugin": "^4.0.5"
  }
  ,"resolutions": {
    "uglifyjs-webpack-plugin/uglify-es": "3.1.6"     //Here
  }
}
```
thanks

**Comment by dan-lee** [comment] 2017-11-09 12:39
@mrjohnr Yes at the top level of your `package.json` is correct.

**Comment by michael-ciniawsky** [comment] 2017-11-10 02:39
Closing as it seems to be unrelated to `uglifyjs-webpack-plugin` in particular, if this is a bug with `uglify-es` itself, please file an issue upstream

**Closed by michael-ciniawsky** 2017-11-10 02:39 UTC
Labels: flag: Needs more info

**Comment by mrjohnr** [comment] 2017-11-10 09:02
Hi.please give me some clues how to fix that and where to search for a fix?thanks
