### ISSUE TITLE
can not support es6 minification after upgrade to 0.4.6

### ISSUE THREAD

**Issue by lili21** [webpack-contrib/uglifyjs-webpack-plugin#49] opened 2017-06-22 07:03 UTC
the `0.4.6` version move the `uglify2` to `dependencies`, so I can't specify the `uglify2` version through `yarn add git://github.com/mishoo/UglifyJS2#harmony-v2.8.22 --dev`. cause the plugin will use its own dependency - `uglify-js^2.8.29`.

**Comment by pkeuter** [comment] 2017-06-22 10:55
Duplicate of #32. See https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/32#issuecomment-300421227 for a workaround.

**Comment by paulpflug** [comment] 2017-06-24 08:28
this is no duplicate.. the workaround doesn't work anymore

**Comment by Hotell** [comment] 2017-06-27 18:09
Yup this is very unfortunate. Patch version breaking stuff... :( https://travis-ci.org/Hotell/typescript-lib-starter/builds/244709499?utm_source=github_status&utm_medium=notification

**Comment by pkeuter** [comment] 2017-06-29 09:33
It is a duplicate. The workaround doesn't work exactly as noted there anymore, but if you change `uglify-js "^2.8.29"` to `uglify-js "^2.8.22"`. Everything is fine. Still an ugly workaround though.

**Comment by lili21** [comment] 2017-06-29 09:49
I don't get it.

**Comment by pkeuter** [comment] 2017-06-29 10:55
```
uglify-js@^2.6, uglify-js@^2.8.22, "uglify-js@git://github.com/mishoo/UglifyJS2#harmony-v2.8.22":
  version "2.8.22"
  resolved "git://github.com/mishoo/UglifyJS2#278577f3cb75e72320564805ee91be63e5f9c806"
  dependencies:
    source-map "~0.5.1"
    yargs "~3.10.0"
  optionalDependencies:
    uglify-to-browserify "~1.0.0"
```
...
```
uglifyjs-webpack-plugin@^0.4.4, uglifyjs-webpack-plugin@^0.4.6:
  version "0.4.6"
  resolved "https://registry.yarnpkg.com/uglifyjs-webpack-plugin/-/uglifyjs-webpack-plugin-0.4.6.tgz#b951f4abb6bd617e66f63eb891498e391763e309"
  dependencies:
    source-map "^0.5.6"
    uglify-js "^2.8.22"
    webpack-sources "^1.0.1"
```

**Comment by lili21** [comment] 2017-06-29 10:59
That is the `yarn.lock` file. I won't say that is a workaround.

**Comment by pkeuter** [comment] 2017-06-29 11:24
It is a workaround, because it works. This is the exact same workaround as posted in #32, with `uglify-js "^2.8.22"` modified from `uglify-js "^2.8.29"`

**Comment by lili21** [comment] 2017-06-29 14:10
There was a better workaround, just run the `yarn add git://github.com/mishoo/UglifyJS2#harmony-v2.8.22 --dev` command. But the `0.4.6` version broken this. that's why I create the issue.

**Comment by kurtextrem** [comment] 2017-06-30 07:33
@pkeuter This is not about the regular versions, but about the harmony branch. If uglifyjs-webpack-plugin states *regular* 2.8.29 as dependency, npm doesn't care if you have the *harmony* branch as dependency set.

**Comment by pkeuter** [comment] 2017-06-30 08:27
@kurtextrem I know this is about the _harmony_ branch, but changing the yarn.lock file as mentioned before, will let this plugin use the older version of the _harmony_ branch of UglifyJS. Again: it's not a brilliant "solution", but it fixes the build for me.

**Comment by michael-ciniawsky** [comment] 2017-07-04 03:41
Will be fixed by #63 soon, currently ES2015 minification isn't supported directly 😞

**Closed by michael-ciniawsky** 2017-07-04 03:41 UTC

**Comment by kurtextrem** [comment] 2017-07-04 06:50
The other question is, why is a patch version breaking things? Just by removing this line: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json#L54 this whole issue would be fixed again.

**Comment by michael-ciniawsky** [comment] 2017-07-04 07:42
@kurtextrem `peerDependency` broke webpack, bc of the missing `uglify` packag, so reverting wouldn't fix it

**Comment by mikesherov** [comment] 2017-07-05 20:29
@kurtextrem also note that for <1.0.0, semver guarantees don't exist.
