### ISSUE TITLE
requestShortener.shorten is not a function

### ISSUE THREAD

**Issue by FranciscoKnebel** [webpack-contrib/uglifyjs-webpack-plugin#197] opened 2017-12-24 20:13 UTC
_Running most recent version of plugin, tested with latest Node LTS (v8.9.3) and latest non-LTS (v9.3.0), on Ubuntu 17.10._

_Workaround_
> While it is not fixed, change the version of uglifyjs-webpack-plugin in package.json manually to ^0.4.6, then run npm install. Thanks  @zjruan.

Related to closed issue #114.
Build fails on minifying the project, aborting the process due to undefined function.
I found the above issue, and since no test case was defined, I've created one below, with test code, which reproduces the bug.

**Test case:**
Created a new project with vue-cli, using the webpack template. I created a repository with the code [here](https://github.com/franciscoknebel/uglifyjs-webpack-plugin-bug-repo), for testing.
Running the dev server compiles everything just fine, but running "npm run build" (production code) fails with this error log:
```
> node build/build.js

⠴ building for production.../home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:272
          return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                                                                                      ^

TypeError: requestShortener.shorten is not a function
    at Function.buildError (/home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:272:87)
    at /home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:206:56
    at Array.forEach (<anonymous>)
    at /home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/index.js:189:21
    at step (/home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /home/francisco/project/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at /home/francisco/project/node_modules/worker-farm/lib/farm.js:191:19
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
Shorten is not a function, so I changed the line requestShortener.shorten(original.source) to only original.source, on the plugin index file, and received the following:
```
> node build/build.js

Hash: 17825dc1377e9e77bff5
Version: webpack 3.10.0
Time: 14542ms
                                                  Asset       Size  Chunks             Chunk Names
               static/js/vendor.5973cf24864eecc78c48.js     111 kB       0  [emitted]  vendor
                  static/js/app.61b6215a7472b1583008.js    15.6 kB       1  [emitted]  app
             static/js/manifest.c6fcda0dc81705d6722b.js    1.49 kB       2  [emitted]  manifest
    static/css/app.742b959f7b6a45229cc87c3e1d1b4e88.css  432 bytes       1  [emitted]  app
static/css/app.742b959f7b6a45229cc87c3e1d1b4e88.css.map  828 bytes          [emitted]  
           static/js/vendor.5973cf24864eecc78c48.js.map     547 kB       0  [emitted]  vendor
              static/js/app.61b6215a7472b1583008.js.map    21.4 kB       1  [emitted]  app
         static/js/manifest.c6fcda0dc81705d6722b.js.map    7.79 kB       2  [emitted]  manifest
                                             index.html  508 bytes          [emitted]  

ERROR in static/js/app.61b6215a7472b1583008.js from UglifyJs
Unexpected token: keyword (var) [/home/francisco/bolsas-vue/node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-61751a6b","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!/home/francisco/bolsas-vue/node_modules/vue-loader/lib/selector.js?type=template&index=0!/home/francisco/bolsas-vue/src/App.vue:4,0][static/js/app.61b6215a7472b1583008.js:49,29]
```
As you can see on the above code, the error reported is an unexpected keyword var, but due to the undefined shorten, the process aborts before reporting, so the error is never thrown. The `static/js/app.61b6215a7472b1583008.js ` file fails right after the second `/* harmony default export */ ` on the following code, according to lines 49/column 29 reported on the error thrown above: 
```
/* harmony default export */ var App = ({
	name: 'app'
});
// CONCATENATED MODULE: ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-b252feb4","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue
var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{attrs:{"id":"app"}},[_c('img',{attrs:{"src":__webpack_require__("7Otq")}}),_vm._v(" "),_c('router-view')],1)}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
/* harmony default export */ var selectortype_template_index_0_src_App = (esExports);
// CONCATENATED MODULE: ./src/App.vue
function injectStyle (ssrContext) {
  __webpack_require__("kEhW")
}
var normalizeComponent = __webpack_require__("VU/8")
```
The full file can be found on the test repository, [here](https://github.com/FranciscoKnebel/uglifyjs-webpack-plugin-bug-repo/blob/master/dist/static/js/app.61b6215a7472b1583008.js). The file will only be saved if the error is thrown, so need to remove the undefined shorten function on the dist/index.js file of the plugin.

If any extra details are needed, feel free to comment. Production code does not work without this.
Wasted too much time trying to find how to fix this.

**Comment by MikeBison** [comment] 2017-12-25 03:53
I have the same error,can you please show more infomation?how to fix?You mean edit the file 'app.js' after build? @FranciscoKnebel

**Comment by FranciscoKnebel** [comment] 2017-12-25 03:56
Hello Mike, haven't found a fix for this yet. There are two bugs here: one
about the shorten function, which breaks the webpack process due to not
existing, and then the minify problem.
I'll wait for someone who knows more about this to take a look first :)

**Comment by MikeBison** [comment] 2017-12-25 04:00
@FranciscoKnebel Thank you!

**Comment by jingle2008** [comment] 2017-12-25 08:00
I ran into the same issue today, looks like it is newly introduced.

**Comment by KonstantinVlasov** [comment] 2017-12-25 08:37
Faced with the same issue after html-minifier was updated to 3.5.8

**Comment by Web-of-Dancer** [comment] 2017-12-25 09:26
@FranciscoKnebel The problem was solved, but new problems arose, and the vue-barcode plug-in introduced by the project was wrong.

**Comment by An0nymous0** [comment] 2017-12-25 09:41
怎么解决？

**Comment by An0nymous0** [comment] 2017-12-25 10:00
No one knows what is the reason for this problem?

**Comment by SuperGod** [comment] 2017-12-25 11:28
I have the same problem

**Comment by deepeshmadkar** [comment] 2017-12-25 11:35
npm prod is working, 
But build is giving error:
TypeError: requestShortener.shorten is not a function

**Comment by sjjgithub** [comment] 2017-12-25 11:48
表示遇到同样的问题

**Comment by littledu** [comment] 2017-12-25 11:56
I have the same problem

**Comment by sjjgithub** [comment] 2017-12-25 12:17
想知道怎么解决

**Comment by zjruan** [comment] 2017-12-25 12:46
我也碰到了同样的问题，但是上周五还是好好的。于是我对比了之前的 `package.json`，发现 `uglifyjs-webpack-plugin` 的版本是 `0.4.6`，但现在已经是`1.1.4`了。于是我又会到这里，发现了`README.md`文件开头的一段话
> webpack =< v3.0.0 currently contains v0.4.6 of this plugin under `webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0

解决方案：将`package.json`中的`uglifyjs-webpack-plugin`的版本手动改为`^0.4.6`，再重新`npm install`

## google translate
I also encountered the same problem, but last Friday is ok. So I compared the previous `package.json `and found` uglifyjs-webpack-plugin` to be `0.4.6`, but it's now` 1.1.4`. So I'll be here again and I found the beginning of the `README.md` file
> webpack = <v3.0.0 currently contains v0.4.6 of this plugin under `webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack .optimize.UglifyJsPlugin is scheduled for webpack v4.0.0

Solution: Change the version of `uglifyjs-webpack-plugin` in` package.json` manually to `^ 0.4.6`, then restart` npm install`

**Comment by zeratul1** [comment] 2017-12-25 16:03
There are two issues.

First, incorrect params of `buildError` function.
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/966987c6d1284b6daf94c814b0899cfe0bc485b3/src/index.js#L56
I think it should be
```
static buildError(err, file, sourceMap, compilation, requestShortener) {
```

Second, the `uglify-es` can not parse source code with inline comment correctly
it can not generate AST from these codes successfully
```
// EXTERNAL MODULE: ./node_modules/vue/dist/vue.esm.js
var vue_esm = __webpack_require__("7+uW");
/* harmony default export */ var App = ({
  name: 'app'
});
```

So downgrade to v0.4.6 is a good solution :D

**Comment by amiram** [comment] 2017-12-25 22:40
I had the uglifyjs problem with inline comments today. My project is built with angular cli. Building with `-prod` ended with an error about the var keyword. Building with source map `-sm` failed silently. The problematic row for uglifyjs was:
`/* harmony default export */ var src_voronoi = (function() {`
No idea why this row in particular. Other rows with such comment were fine.
Eventually uglifyjs fixed the issue in version 3.3.2.

**Comment by evilebottnawi** [comment] 2017-12-26 08:39
@amiram known issue https://github.com/mishoo/UglifyJS2/issues/2500

**Comment by evilebottnawi** [comment] 2017-12-26 08:41
Seems something wrong in uglify-es, i strongly recommend use lock files to avoid this problem, also somebody can provide uglify-es version?

**Comment by evilebottnawi** [comment] 2017-12-26 08:55
@kzc friendly ping, regression(s) in `uglify-es`?

**Comment by raj7831** [comment] 2017-12-26 10:00
There are errors in "uglify-es" file for sure. To solve issue I have shifted "uglify-es" to lower version, which solved the issue. But whats wrong in newer version!! Still finding.

**Comment by kzc** [comment] 2017-12-26 14:39
> friendly ping, regression(s) in uglify-es?

The comment parse issue https://github.com/mishoo/UglifyJS2/issues/2652 was fixed in `uglify-es@3.3.2`.

As for other issues in this thread, users would have to create an uglify input file that would reproduce the problem. Posting the error alone is rarely helpful.

**Comment by kzc** [comment] 2017-12-26 14:46
@evilebottnawi `requestShortener.shorten` is code found in `uglifyjs-webpack-plugin@1.x`. `uglifyjs-webpack-plugin@1.x` does not report uglify errors correctly.

Please see: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/114#issuecomment-326427192

**Comment by evilebottnawi** [comment] 2017-12-26 14:56
@FranciscoKnebel problem still exists?

**Comment by kzc** [comment] 2017-12-26 15:00
@evilebottnawi Just to be clear, unrelated to the uglify comment parse bug, there's still a bug in `uglifyjs-webpack-plugin@1.x` that was never resolved. Not sure why https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/114 was closed. Create a JS file with invalid ES6 input and feed it through this plugin.

**Comment by FranciscoKnebel** [comment] 2017-12-26 15:41
@kzc hey, thanks for helping clarify things. On the repository and on the original comment, I have inserted a test file which should trigger the uglify error. The point of creating the issue was to fix the plugin silent failure, which was found on a months old issue that was closed unresolved, due to not having a test case.

@evilebottnawi rollbacking into v0.4.6 is a workaround for the problem with uglify.

**Comment by zeratul1** [comment] 2017-12-27 07:14
@evilebottnawi 
please the first issue in my comment above.

> First, incorrect params of buildError function.
This causes a TypeError: requestShortener.shorten is not a function
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/966987c6d1284b6daf94c814b0899cfe0bc485b3/src/index.js#L56
I think it should be
>```static buildError(err, file, sourceMap, compilation, requestShortener) {```

**Comment by evilebottnawi** [comment] 2017-12-27 09:54
@zeratul1 can you provide minimum reproducible test repo?

**Comment by kzc** [comment] 2017-12-27 15:37
@evilebottnawi A test case would be any invalid ES6 input fed to this plugin. As @zeratul1 mentioned, please examine the function parameters - `compilation` is missing:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/966987c6d1284b6daf94c814b0899cfe0bc485b3/src/index.js#L56

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/966987c6d1284b6daf94c814b0899cfe0bc485b3/src/index.js#L169

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/966987c6d1284b6daf94c814b0899cfe0bc485b3/src/index.js#L186

**Closed** 2018-01-04 19:00 UTC
Labels: flag: Has pull request, priority: 2 (urgent), severity: 3 (broken), type: Bug
