### ISSUE TITLE
`include` isn't currently working

### ISSUE THREAD

**Issue by hulkish** [webpack-contrib/uglifyjs-webpack-plugin#79] opened 2017-07-10 23:31 UTC
I'm unfamiliar with the history of the [include option](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#options). So, I went looking and couldn't find a single mention of it in source code of `uglifyjs-webpack-plugin`, `uglify-es` or `uglify-js`. 

> **Update**: I've since learned it comes from `webpack/lib/ModuleFilenameHelpers`'s `ModuleFilenameHelpers.matchObject()` method. The problem, however is that `include`/`exclude` really only applies to `compilation.assets`. 

> So to make this fully functional IMO, (feature?) - we should probably implement #21. Which would allow us to match against module paths.

I wrote this test to prove it:
```js
import UglifyJsPlugin from '../src/index';
import {
  cleanErrorStack,
  createCompiler,
  compile,
} from './helpers';

describe('when applied with include option', () => {
  it('matches snapshot', () => {
    const compiler1 = createCompiler();
    const compiler2 = createCompiler();
    new UglifyJsPlugin().apply(compiler1);
    new UglifyJsPlugin({
      uglifyOptions: {
        include: /foo\.js$/,
        compress: true,
      },
    }).apply(compiler2);

    return Promise.all([
      compile(compiler1).then((stats) => {
        const errors = stats.compilation.errors.map(cleanErrorStack);
        const warnings = stats.compilation.warnings.map(cleanErrorStack);

        expect(errors).toMatchSnapshot('errors');
        expect(warnings).toMatchSnapshot('warnings');

        for (const file in stats.compilation.assets) {
          if (Object.prototype.hasOwnProperty.call(stats.compilation.assets, file)) {
            expect(stats.compilation.assets[file].source()).toMatchSnapshot(file);
          }
        }

        return stats;
      }),
      compile(compiler2).then((stats) => {
        const errors = stats.compilation.errors.map(cleanErrorStack);
        const warnings = stats.compilation.warnings.map(cleanErrorStack);

        expect(errors).toMatchSnapshot('errors');
        expect(warnings).toMatchSnapshot('warnings');

        for (const file in stats.compilation.assets) {
          if (Object.prototype.hasOwnProperty.call(stats.compilation.assets, file)) {
            expect(stats.compilation.assets[file].source()).toMatchSnapshot(file);
          }
        }

        return stats;
      }),
    ]).then(([stats1, stats2]) => {
      expect(Object.keys(stats1)).toEqual(Object.keys(stats2));

      for (const file in stats1.compilation.assets) {
        if (Object.prototype.hasOwnProperty.call(stats1.compilation.assets, file)) {
          expect(stats1.compilation.assets[file].source()).toEqual(stats2.compilation.assets[file].source());
        }
      }
    });
  });
});
```

This outputs a snapshot:
```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`errors 1`] = `Array []`;

exports[`errors 2`] = `Array []`;

exports[`main.0c220ec66316af2c1b24.js 1`] = `"webpackJsonp([0],[function(o,n){o.exports=function(){console.log(7)}}],[0]);"`;

exports[`main.0c220ec66316af2c1b24.js 2`] = `"webpackJsonp([0],[function(o,n){o.exports=function(){console.log(7)}}],[0]);"`;

exports[`manifest.6afe1bc6685e9ab36c1c.js 1`] = `"!function(e){function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}var r=window.webpackJsonp;window.webpackJsonp=function(t,c,a){for(var i,u,f,l=0,s=[];l<t.length;l++)u=t[l],o[u]&&s.push(o[u][0]),o[u]=0;for(i in c)Object.prototype.hasOwnProperty.call(c,i)&&(e[i]=c[i]);for(r&&r(t,c,a);s.length;)s.shift()();if(a)for(l=0;l<a.length;l++)f=n(n.s=a[l]);return f};var t={},o={1:0};n.e=function(e){function r(){i.onerror=i.onload=null,clearTimeout(u);var n=o[e];0!==n&&(n&&n[1](new Error(\\"Loading chunk \\"+e+\\" failed.\\")),o[e]=void 0)}var t=o[e];if(0===t)return new Promise(function(e){e()});if(t)return t[2];var c=new Promise(function(n,r){t=o[e]=[n,r]});t[2]=c;var a=document.getElementsByTagName(\\"head\\")[0],i=document.createElement(\\"script\\");i.type=\\"text/javascript\\",i.charset=\\"utf-8\\",i.async=!0,i.timeout=12e4,n.nc&&i.setAttribute(\\"nonce\\",n.nc),i.src=n.p+\\"\\"+e+\\".\\"+({0:\\"main\\"}[e]||e)+\\".\\"+{0:\\"0c220ec66316af2c1b24\\"}[e]+\\".js\\";var u=setTimeout(r,12e4);return i.onerror=i.onload=r,a.appendChild(i),c},n.m=e,n.c=t,n.d=function(e,r,t){n.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:t})},n.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(r,\\"a\\",r),r},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p=\\"\\",n.oe=function(e){throw console.error(e),e}}([]);"`;

exports[`manifest.6afe1bc6685e9ab36c1c.js 2`] = `"!function(e){function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}var r=window.webpackJsonp;window.webpackJsonp=function(t,c,a){for(var i,u,f,l=0,s=[];l<t.length;l++)u=t[l],o[u]&&s.push(o[u][0]),o[u]=0;for(i in c)Object.prototype.hasOwnProperty.call(c,i)&&(e[i]=c[i]);for(r&&r(t,c,a);s.length;)s.shift()();if(a)for(l=0;l<a.length;l++)f=n(n.s=a[l]);return f};var t={},o={1:0};n.e=function(e){function r(){i.onerror=i.onload=null,clearTimeout(u);var n=o[e];0!==n&&(n&&n[1](new Error(\\"Loading chunk \\"+e+\\" failed.\\")),o[e]=void 0)}var t=o[e];if(0===t)return new Promise(function(e){e()});if(t)return t[2];var c=new Promise(function(n,r){t=o[e]=[n,r]});t[2]=c;var a=document.getElementsByTagName(\\"head\\")[0],i=document.createElement(\\"script\\");i.type=\\"text/javascript\\",i.charset=\\"utf-8\\",i.async=!0,i.timeout=12e4,n.nc&&i.setAttribute(\\"nonce\\",n.nc),i.src=n.p+\\"\\"+e+\\".\\"+({0:\\"main\\"}[e]||e)+\\".\\"+{0:\\"0c220ec66316af2c1b24\\"}[e]+\\".js\\";var u=setTimeout(r,12e4);return i.onerror=i.onload=r,a.appendChild(i),c},n.m=e,n.c=t,n.d=function(e,r,t){n.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:t})},n.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(r,\\"a\\",r),r},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p=\\"\\",n.oe=function(e){throw console.error(e),e}}([]);"`;

exports[`warnings 1`] = `Array []`;

exports[`warnings 2`] = `Array []`;
```

As you can see, it is ignoring the `include` option entirely and uglifying everything (identical compilation output for both). Is this still a desired feature? 

This also makes me wonder; are there other options are obsolete/no longer working? 

**Update**I think this is also true for the `test`/`exclude` options.

**Comment by hulkish** [comment] 2017-07-12 12:12
Can be solved by a pr for #21

**Comment by evilebottnawi** [comment] 2017-07-12 12:26
strangely, seems your are right,  we need implement #21

**Comment by mikesherov** [comment] 2017-07-27 18:15
So is this just a dupe of #21 then and can we close this?

**Comment by michael-ciniawsky** [comment] 2017-07-27 19:28
Yep, closing in favour of #21

**Closed by michael-ciniawsky** 2017-07-27 19:28 UTC
Labels: priority: 4 (important), severity: 3 (broken), type: Bug
