### ISSUE TITLE
NameCache option and parallel option do not work together

### ISSUE THREAD

**Issue by truebden** [webpack-contrib/uglifyjs-webpack-plugin#312] opened 2018-06-15 09:29 UTC
### Current: ###
If you enabled the option parallel and the uglifyOption nameCache. The name cache is always empty.
### Example: ###
```
    var nameCache = {};
    plugins: [ew UglifyJSPlugin({
        uglifyOptions: {
            nameCache: nameCache
        },
        parallel: true
    })]
```
### Tested with versions: ###
```
    "uglifyjs-webpack-plugin": "1.2.5",
    "webpack": "3.12.0",
```

### Expected: ###
Either enhance documentation that this is not possible (due to no possibility of syncing the cache) and show a log message if both options are used. Or ensure the nameCache is filled even if parallel option is enabled.

**Comment by evilebottnawi** [comment] 2018-06-15 09:40
@truebden we don't have option `nameCache`, also `cache` and `parallels` disable by default for best practice, use `parallels: true` and `cache: true`

**Comment by truebden** [comment] 2018-06-15 09:51
@evilebottnawi yes, but it is an option for propagated to uglifyjs, which does not work with your parallel option as it does not return any name cache.
Also the nameCache is something different to the cache option from you. I guess it only caches some output and not the mapping between original to obfuscated identifiers.

**Comment by evilebottnawi** [comment] 2018-06-15 09:56
@truebden hm, you are right, feel free to send a PR to solve this problem, we should save `nameCache` between each compilation

**Comment by truebden** [comment] 2018-06-15 10:15
@evilebottnawi Maybe you can give me a hint about it. Because I think you would need a synchronized access to the name cache for all parallel running uglifyjs instances. For this I checked in uglifyjs code if it would be possible to define some callback for each identifier to mangle. But there is no such feature.

If it is not possible to synchronize the access, each process would override the map.

**Comment by evilebottnawi** [comment] 2018-06-15 10:21
@truebden you should return `nameCache` from minify and put this into cache (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/uglify/index.js#L60), also get `nameCache` from cache (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/uglify/index.js#L68) and pass this in minify function

**Comment by truebden** [comment] 2018-06-15 10:27
@evilebottnawi I am not sure if this would be enough. For instance, if you have 2 processes for uglifyjs and they are started in parallel. Then both of them will work with an empty nameCache and fill it as they need. As they are 2 process, I assume these are not using the same instance of the nameCache object, but 2 different ones. But actually they would need to shared it between the processes. What do you think?

**Comment by evilebottnawi** [comment] 2018-06-15 10:30
@truebden for each file `cache` object will be individual, because we use `path` and `content` as part of cache key

**Comment by truebden** [comment] 2018-06-15 10:38
@evilebottnawi okay, but when you use the nameCache, you typically want to share the same obfuscation identifiers between all output files (at least for me this is important).

**Comment by evilebottnawi** [comment] 2018-06-15 10:51
@truebden check `nameCache` option on enable and save all outputs in one cache object, PR welcome, it is hard to speak without minimum implementation

**Comment by kzc** [comment] 2018-07-10 16:49
The uglify (or terser) name cache cannot work in parallel by design. The mangling of each module must be done serially. `uglifyjs-webpack-plugin` should error out if both options are enabled.

**Comment by evilebottnawi** [comment] 2018-07-10 16:51
@kzc Thanks!

**Comment by kzc** [comment] 2018-07-10 17:01
> The uglify (or terser) name cache cannot work in parallel by design. The mangling of each module must be done serially.

Furthermore, the nameCache object is read/write and the same object instance must be passed to all `minify()` invocations in a chunking scenario.

https://github.com/fabiosantoscode/terser#minify-options

- `nameCache` (default `null`) - pass an empty object `{}` or a previously
  used `nameCache` object if you wish to cache mangled variable and
  property names across multiple invocations of `minify()`. Note: this is
  a read/write property. `minify()` will read the name cache state of this
  object and update it during minification so that it may be
  reused or externally persisted by the user.

**Closed** 2018-09-17 06:11 UTC
Labels: priority: 5 (nice to have), semver: Minor, type: Feature
