### ISSUE TITLE
souce map does not work with standard options

### ISSUE THREAD

**Issue by shkrishms** [webpack-contrib/uglifyjs-webpack-plugin#116] opened 2017-08-30 22:43 UTC
Hi,
I am using uglify as a part of webpack and I am not able to get the sourcemap working properly. I want to enable sourcemaps to get a better stack trace for errors. I still see cryptic errors. 

When i remove the UglifyJS plugin from the webpack, it works fine i.e I see the correct stack traces and I see a "sourceMappingURL" line in the js bundles.

With UglifyJS and sourcemap enabled, I see that map files are being generated (js.map in the build) but I do not find the "sourceMappingURL" line in the js bundles. and the stacktraces are from the minified code.

**webpack.config.js**
```js
 devtool: "source-map"
 // Plugins
[
      new ForkTsCheckerWebpackPlugin({
          some options
        }),
        new webpack.optimize.CommonsChunkPlugin({
            names: ["x1", "x2", "x3", "x4", "manifest"],
        }),
        new webpack.DefinePlugin(),
        extractLess,
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            },
            sourceMap: true
        }),
        // new BundleAnalyzerPlugin(),
        new HtmlWebpackPlugin({
            filename: "../index.html",
            template: "./config/template.html"
        }),
]
```

> edited by @michael-ciniawsky (Formatting)

**Comment by evilebottnawi** [comment] 2017-08-31 10:10
@shkrishms can you create minimum reproducible test repo, thanks!

**Comment by michael-ciniawsky** [comment] 2017-08-31 13:36
@shkrishms Could you try with the latest `beta` please ?

```
npm i -D uglifyjs-webpack-plugin@beta
```

But for `development` (debugging etc) I recommend to not use a minifier

**webpack.config.js**
```js
const env = process.env.NODE_ENV

{
   plugins: [ env === 'development' ? new UglifyJSPlugin() : false ].filter(Boolean)
}
```

**Comment by shkrishms** [comment] 2017-09-01 23:18
@michael-ciniawsky , the beta does not seem to help.
I have created a repository at https://github.com/shkrishms/UglifyJsIssue. This should have the code necessary to reproduce the issue.

Please use chrome only.
Go to the OspApp folder. and then do the following:
1. npm run build:prod
2. npm run start:release
3. Open https://localhost:44326 in the browser and see the sources.

"\OspApp\config\webpack.prod.js" has the config for UglifyJS. When UglifyJS plugin is removed, the stack trace is correctly reproduced.

**Comment by shkrishms** [comment] 2017-09-06 17:19
@michael-ciniawsky , @evilebottnawi -, any update on this? Please let me know if anything is needed.

**Comment by evilebottnawi** [comment] 2017-09-06 18:21
@shkrishms sorry, don't have time right now for this :disappointed: in near future i try to investigate this, thanks!

**Comment by michael-ciniawsky** [comment] 2017-10-21 03:21
Closing in favour of #134

**Closed by michael-ciniawsky** 2017-10-21 03:21 UTC
Labels: flag: Needs more info

**Comment by nicewahson** [comment] 2018-08-14 01:54
I am in the same situation now. i'm using webpack4 and it looks like not working with option sourceMap true
