### ISSUE TITLE
Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script

### ISSUE THREAD

**Issue by linija-kalloopparambil** [webpack-contrib/uglifyjs-webpack-plugin#159] opened 2017-11-06 14:46 UTC
npm -v
5.5.1
node -v
v8.9.0

when trying to install the angular cli i get this error
npm install -g @angular/cli
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Windows\scripts\install.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.

**Comment by evilebottnawi** [comment] 2017-11-08 09:35
@linija-kalloopparambil old version have problem on windows in `postinstall` file, can you use latest version of `uglifyjs-webpack-plugin`?

**Comment by michael-ciniawsky** [comment] 2017-11-08 19:36
Duplicate of #129

**Closed by michael-ciniawsky** 2017-11-08 19:36 UTC

**Comment by Soorya-S** [comment] 2018-06-26 05:15
same issue...still ans in #129 does'nt work
