### ISSUE TITLE
minify function/documentation limitations

### ISSUE THREAD

**Issue by luzat** [webpack-contrib/uglifyjs-webpack-plugin#331] opened 2018-07-22 00:19 UTC
Minify functions (and possibly others) do hardly work with parallel enabled, because their scopes are not available in the workers. I was trying to pass terser in as a variable or `require('terser')` within minify, but both failed because either `terser` or `require` were undefined with `parallel: true`. I am not sure if there is any possible workaround? It works fine with `parallel: false`. This should at least be somehow documented.

Also, the syntax

```js
{
  minify(file, sourceMap) {
    // ...
  }
}
```

as used in the documentation is not supported by Node by default currently and probably will not work in a webpack.config.js, but at best within webpack.config.babel.js. The shortest alternative is probably:

```js
{
  minify: (file, sourceMap) => {
    // ...
  }
}
```

This happens with 0174605fdf7b0eb8dc3b18aaec262d1e757e6863 in Webpack 4.16.2 running on Node 10.7.0.

**Comment by evilebottnawi** [comment] 2018-07-23 08:17
@luzat please provide example, all works fine in parallel true/false

**Comment by luzat** [comment] 2018-07-23 14:11
I set up a demo repository: https://github.com/luzat/parallel-uglify-bug

I haven't looked too much into it, but the options evaluation in works.js looks dubious and probably breaks things?

**Comment by evilebottnawi** [comment] 2018-07-23 14:44
@luzat thanks for repo :+1: In todo list

**Comment by evilebottnawi** [comment] 2018-07-25 16:18
Confirmed, WIP

**Comment by evilebottnawi** [comment] 2018-07-25 17:39
@luzat i fix `require` (i.e. exports, require, module, __filename and __dirname will be available), but i can't fix it for https://github.com/luzat/parallel-uglify-bug/blob/master/webpack.config.js#L11, because foo is not available. You can use `shared-memory` for this purpose (https://www.npmjs.com/search?q=shared%20memory)

**Comment by luzat** [comment] 2018-07-25 20:17
My use case at first was just requiring terser as mentioned in the documentation. I solved this by having yarn resolve uglify-es to terser in the package.json instead:

```
  "resolutions": {
    "uglify-es": "npm:terser"
  }
```

The minify option should include some notice about this behavior, though. Not sure if this also applies to other functions (cacheKeys, extractComments?)? I would guess that this option would become superfluous for most people with terser becoming standard (and some other optimization option for Webpack 5?). Thanks for yout time and effort!

**Comment by filipesilva** [comment] 2018-07-26 15:52
@evilebottnawi do you mean using https://github.com/ericdum/node-shared-memory is required when computed uglify options are used?

**Comment by evilebottnawi** [comment] 2018-07-26 15:58
@filipesilva any implementation of shared memory if you enable parallel and want share information between main process and minify function

**Comment by evilebottnawi** [comment] 2018-07-26 16:01
@filipesilva better wait terser webpack plugin, i think i will release on next week

**Comment by filipesilva** [comment] 2018-07-26 16:02
Yeah I was tinkering with this a bit to see how it would help Angular CLI users. @sanderelias tried out resolving `uglify-es` to `terser` (using @luzat's [method](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/331#issuecomment-407881544)) and that really helped on a big project he had. Around 60% faster prod builds.

**Comment by evilebottnawi** [comment] 2018-07-26 16:15
It is very good :+1:

**Comment by kzc** [comment] 2018-07-26 16:40
> do you mean using https://github.com/ericdum/node-shared-memory is required when computed uglify options are used with parallel builds?

@filipesilva fyi - possibly off-topic - some uglify/terser options such as property mangling are not compatible with parallel operation by design:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/312#issuecomment-403891532

Even shared memory won't help in such a case due to race conditions accessing/updating the name cache object.

**Comment by filipesilva** [comment] 2018-07-26 16:41
IIRC does parallelism by processed file, which I think is a boundary that uglify never crosses. Is my understanding incorrect?

**Comment by kzc** [comment] 2018-07-26 17:33
Uglify/Terser was never designed with parallel operation in mind. If you have related JS inputs that would require a shared nameCache (for common mangled variables, property mangling or whatever) then it would not work in parallel. I suppose if the JS inputs were standalone/unrelated and do not share a `nameCache` object then conceivably a plugin could run such `minify` operations in parallel if coded correctly. Whether this plugin does this, I don't know.

**Closed** 2018-07-27 10:51 UTC
Labels: priority: 4 (important), semver: Patch, severity: 3 (broken), type: Bug
