### ISSUE TITLE
Question: Switch to maintained uglification module?

### ISSUE THREAD

**Issue by sirreal** [webpack-contrib/uglifyjs-webpack-plugin#262] opened 2018-03-19 09:48 UTC
It appears that `uglify-es` will not be maintained. See https://github.com/mishoo/UglifyJS2/issues/2908#issuecomment-367686007 and https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-374147334.

There are [known issues](https://github.com/mishoo/UglifyJS2/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug+label%3Aharmony) which affect the behavior of code transformed by `uglify-es`. I recently came across a pesky production only bug (https://github.com/Automattic/wp-calypso/issues/21489) which was caused by an issue with `uglify-es` (https://github.com/mishoo/UglifyJS2/issues/3010).

I'd like to consider what can be done to ensure that this plugin reliably transforms code that will maintain the same behavior as pre-transform code. Some ideas:

- Switch to `uglify-js`
- Switch to another module like `babel-minify` (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264#issuecomment-374536624)
- Use a set of default options that disable uglification features known to be problematic (#264, #265)
- Encourage contributions to port `uglify-js` fixes to `uglify-es`

cc: @jsnajdr @ockham

**Comment by evilebottnawi** [comment] 2018-03-19 10:00
@sirreal thanks for issue, let's wait response from other contributors, i confused why `uglify-es` will not be maintained. How we can handle es5+ syntax

**Comment by sirreal** [comment] 2018-03-20 12:11
> How we can handle es5+ syntax 😕 ?

Not sure if this question is for me or other maintainers. I'll just reference #264 proposing a `babel-minify` as an alternative (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264#issuecomment-374536624).

**Comment by estaub** [comment] 2018-03-20 13:56
@evilebottnawi - see comments on mishoo/UglifyJS2/issues/3010, mishoo/UglifyJS2/issues/2842

...which suggests another option, a wee bit out of scope: use a forked, maintained uglify-es (a.k.a. "harmony" in the comments).

**Comment by evilebottnawi** [comment] 2018-03-20 14:08
@estaub do you have time to maintenance new package?

**Comment by estaub** [comment] 2018-03-20 14:39
@evilebottnawi I've not the skill, and if it wasn't obvious, I was being ironic in calling it "a wee bit out of scope"!  But this is a big enough problem that someone might pick it up and/or fund it.

Also, if anyone personally knows Alex, the developer who's dropping support for uglify-es, they might want to reach out and try to understand better where he's at.  uglify-es has been a huge contribution; if there are conditions under which he'd want to continue with it, he's owed every opportunity.

**Comment by Reinmar** [comment] 2018-03-22 19:41
I found this issue when we encountered the problems described in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264. 

If I understand it correctly, webpack 4 introduced a production mode which defaults to uglifyjs-webpack-plugin which, in turn, relies on uglify-es. This is all a bit odd, taken that uglify-es is not maintained anymore.

I know that making long-term decisions in the JS world is hard, especially for OSS projects which need to consider backwards compatibility and trends. So, I can't tell you that going with babel-minify is the best choice. However, what I can tell from my own experience (and preference) is that:

* Speed doesn't have to be the most important factor; reliability is more important,
* We use babel-minify to build [CKEditor 5](https://github.com/ckeditor/ckeditor5) (fairly big ES6 project) for about a year now and we had one issue so far (which was fixed),
* The idea to use Babel (or babylon to be precise) as a base of a minifier sounds quite future-proof. New versions of ES should be supported (at least in this aspect) out of the box as long as Babel will be maintained. As far as I can understand, uglify-es has a built-in parser which means that its maintainer will need to catch up with new ES versions.

**Comment by ojab** [comment] 2018-04-06 10:05
babel-minify is also barely maintained, see https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68.

**Comment by evilebottnawi** [comment] 2018-04-13 09:50
@whtsky why you create forn, why just don't send PR in this repo?

**Comment by evilebottnawi** [comment] 2018-04-13 09:51
Also don't worry after small fixes with source map and memory leak i will implement this :+1:

**Comment by whtsky** [comment] 2018-04-13 10:04
@evilebottnawi   `uglify-js` doesn't support ES6 so it's a breaking change.  I'd be happy to send PR if you guys decides to do that :)

**Comment by evilebottnawi** [comment] 2018-04-13 10:20
@whtsky why do breaking changes? By default we can still use `uglify-es`, just allow pass `minify` function as option, it is allow people use `uglify-js`. `uglify-es` return same output as `uglify-js`. Here https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/uglify/minify.js#L150 add check on function and if it function run function instead `uglify-es`. Also some improve docs about this feature.

**Comment by whtsky** [comment] 2018-04-13 10:25
@evilebottnawi simply allow pass `minify` function as an option may not be enough since `uglifyjs-webpack-plugin` uses uglify-es as a part of cache key

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/693e45ea74cad073072b8b226bf314b6546e6738/src/index.js#L164

**Comment by evilebottnawi** [comment] 2018-04-13 10:33
@whtsky it is not break, we use https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/693e45ea74cad073072b8b226bf314b6546e6738/src/index.js#L166 options as cache key and if you change something in options (i.e. change code of minify function) you invalidate cache. Also for better code, you can rename `uglify-es` in `uglify` and add check in `versions` on installed on top uglify-js/es version

**Comment by whtsky** [comment] 2018-04-13 10:42
@evilebottnawi I don't think it's safe since internally `uglifyjs-webpack-plugin` uses `String` to generate keys
https://github.com/yahoo/serialize-javascript/blob/master/index.js#L84
and options might not change if user switch from `uglify-es` to `uglify-js` or upgrading `uglify-js`.

> add check in versions on installed on top uglify-js/es version

I think it might not be accurate as if user upgraded `uglify-es`, `require` inside `uglify-webpack-plugin` will still get the older version specified in `uglify-webpack-plugin`'s package.json, thus will not invalidate cache

**Comment by evilebottnawi** [comment] 2018-04-13 10:49
@whtsky 
>  Also for better code, you can rename uglify-es in uglify and add check on version installed on top node_modules

**Comment by whtsky** [comment] 2018-04-13 10:56
@evilebottnawi 
I'm not sure how to get the version installed on top node_modules, could you give me an example?

also, it might still be not accurate since the `minify` we received might not from the top node_modules.(user bundled a forked uglifyjs w/ their source code, for example)

**Comment by kzc** [comment] 2018-04-27 06:26
@evilebottnawi @sokra It is recommended that `uglifyjs-webpack-plugin` switch to [@fabiosantoscode/uglify-es](https://www.npmjs.com/package/@fabiosantoscode/uglify-es) which is maintained. It's a drop in replacement for `uglify-es`. 

Unfortunately this `uglify-es` [fork](https://github.com/fabiosantoscode/uglify-es) was not able to obtain `npm` publish rights to the `uglify-es` package name from its owner. This fork may undergo a name change at some point.

**Comment by evilebottnawi** [comment] 2018-04-27 10:36
@kzc Thanks!

**Comment by evilebottnawi** [comment] 2018-04-27 10:37
@kzc Looks uglify-es right now is maintained, right?

**Comment by kzc** [comment] 2018-04-27 12:42
> Looks uglify-es right now is maintained, right?

The npm module named "[`uglify-es`](https://www.npmjs.com/package/uglify-es)" is not presently maintained.

The scoped npm module named "[`@fabiosantoscode/uglify-es`](https://www.npmjs.com/package/@fabiosantoscode/uglify-es)" is presently maintained.

You may elect to update `uglifyjs-webpack-plugin`'s dependency in `package.json`, the plugin code, and the documentation links accordingly. A beta release of `uglifyjs-webpack-plugin` with this change might be prudent.

**Comment by evilebottnawi** [comment] 2018-04-27 12:46
@kzc what is current status `@fabiosantoscode/uglify-es`, it is stable? Also maybe we can resolve meta issues first - example use new name for issue, also implement changelog/release page about features/changes/fixes. We should provide long term support this plugin for webpack and hard to do this without this stuff. Thanks!

**Comment by evilebottnawi** [comment] 2018-04-27 12:49
My suggestion is move `uglify-es` to `org` repo (tomorrow some people can be unavailable and it can kill project), improve readme and move uglify-es issue to this repo (as known issues).

**Comment by kzc** [comment] 2018-04-27 12:54
@evilebottnawi It is what it is. As with all this stuff it's a volunteer effort. No one is paid to work on it. Nothing ever was, or is, guaranteed.

You're welcome to use `@fabiosantoscode/uglify-es` if you like. Or perhaps `webpack` can make and maintain its own `uglify-es` fork and do the things you mentioned.

**Comment by kzc** [comment] 2018-04-27 14:03
@evilebottnawi You're asking for guarantees that were never present in `uglify-js` or `uglify-es`. This issue raised the question of switching to a maintained uglify module for ES6+. I was responding to that question with a maintained `uglify-es` fork with bug fixes for known issues. If you don't wish to use it, no problem.

**Comment by evilebottnawi** [comment] 2018-04-27 14:10
@kzc we want use, why you so rude? Just we want ensure when we switch on fork above it is not die after one/two weeks.

**Comment by kzc** [comment] 2018-04-27 14:24
> why you so rude? 

@evilebottnawi What are you talking about? Nothing I wrote was rude. I can't say the same for your remarks. 

I regret trying to help the webpack project.

**Comment by evilebottnawi** [comment] 2018-04-27 14:40
@kzc You look like a small child now.

We use this plugin for very very very large community and each change can break build process of many peoples. Now you try to switch on repo which even have actual CHANGELOG/Release page - i don't know what i should say people why their code broken after upgrade (if we switch on fork). My suggestion is improve organization of project and all. I can not understand the complexity of solving these issues, if you need help just tell me what i can do and I will help you.

It's easy to say that no one is obliged to anyone, but I think this approach is not acceptable for me and for projects which I am responsible. I'm always open for improvements/innovations and discussion.

If you need money for work, you can take part in dozens of projects that pay money for contributing to open source project. Do not constantly state that you are doing it for free. I'm just like you and I also do it on a voluntary basis.

I really hope that you do not take it personally, all of the above is my opinion. I'm open to any help, just create issue and ping me. Anyways thanks for help!

**Comment by kzc** [comment] 2018-04-27 15:34
> @kzc You look like a small child now.

@evilebottnawi Wow. Are you for real?

> We use this plugin for very very very large community and each change can break build process of many peoples. Now you try to switch on repo which even have actual CHANGELOG/Release page - i don't know what i should say people why their code broken after upgrade (if we switch on fork). 

Give me a break. How was that different from any of the `uglify-es` releases? If you look at the commit history of both projects you'll see that two of the `@fabiosantoscode/uglify-es` maintainers are long time `uglify-js` and `uglify-es` contributors. One of them is the initial author of the UglifyJS2 harmony branch for ES6+ support. No code is bug free, but this `uglify-es` fork contains fewer bugs than the one `webpack@4` is already using. Like the original project, the fork contains an extensive test suite to ensure quality and avoid regressions.

I'm not looking for any advice from you. I was just pointing out the demands you are making about the quality of the new module are different from the criteria when `uglify-es` - or even `uglify-js` - was selected by webpack in the first place. Literally the only difference is the module name, which I mentioned in my first comment could be subject to change.

**Comment by evilebottnawi** [comment] 2018-04-27 15:45
@kzc note about 

> If you look at the commit history of both projects you'll see that two of the @fabiosantoscode/uglify-es maintainers are long time uglify-js and uglify-es contributors. One of them is the initial author of the UglifyJS2 harmony branch for ES6+ support.

is very good for me, sorry, i don't know about this. In near future i will try to switch and looks on tests.

@fabiosantoscode Just glad to hear you opinion here.

**Comment by fabiosantoscode** [comment] 2018-04-27 22:05
I think you should go ahead and make the change! The new package is the way forward.

**Comment by fabiosantoscode** [comment] 2018-04-27 22:05
We'll have a new name soon so I'll be sure to drop by then

**Comment by evilebottnawi** [comment] 2018-04-28 09:33
@fabiosantoscode maybe better switch on new repo after resolve issue around name? We don't want do multiple release. How fast is the problem to be solved?

**Comment by fabiosantoscode** [comment] 2018-04-28 22:05
I'm not sure how long it will take. We have to come up with a name, and if the name is reserved we have to go through due process.

**Comment by syranide** [comment] 2018-06-01 19:56
@fabiosantoscode Any particular reason why the dependency switch to `terser` hasn't been made yet?

**Comment by evilebottnawi** [comment] 2018-06-01 20:00
@syranide wait after some projects test this

**Comment by syranide** [comment] 2018-06-01 20:05
@evilebottnawi Thank you, is there an alpha/beta of this plugin with updated depdency that I can use to test? If https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/262#issuecomment-393993505 gets merged and I can get it merged into terser then I'm very interested in running it against my work software.

**Comment by evilebottnawi** [comment] 2018-06-01 20:09
@syranide we will do this in near future, sorry for delay

**Comment by mgol** [comment] 2018-06-11 15:23
The fact `uglify-es` is unmaintained is only one problem. Another is `uglifyjs-webpack-plugin` relies on `uglify-es` even if minifying ES5 code (by passing a proper `ecma` option) as it's easier to rely on one package than on two. It should depend on two packages, though, then at least ES5 compilation would be stable and battle-tested, ES6+ minification is still very experimental, unfortunately.

**Comment by evilebottnawi** [comment] 2018-07-03 14:09
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/298 (major release) and https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/321 (manor release `1.3.0`)

**Closed by evilebottnawi** 2018-07-03 14:09 UTC
Labels: priority: 1 (critical), severity: 3 (broken), status: Needs triage
