### ISSUE TITLE
[v1.0.0-beta.2 (Windows)] Stuck in chunk assets optimization when parallelization is enabled (`options.parallel`)

### ISSUE THREAD

**Issue by jinker** [webpack-contrib/uglifyjs-webpack-plugin#118] opened 2017-09-01 02:36 UTC
webpack 3.5
windows 7

**Comment by michael-ciniawsky** [comment] 2017-09-01 05:52
Please provide more info on your setup `webpack.config.js` `package.json`  && Error Logs etc aswell

**Comment by kumarharsh** [comment] 2017-09-13 07:20
+1 it's not working under Windows 10 CU - tested in two different systems with different processors and SSD/HDDs. The webpack process takes about 1GB memory but 0% CPU utilization.

This is the uglify config:

```
          uglifyOptions: {
            compress: { warnings: false },
          },
          sourceMap: true,
          parallel: {
            cache: path.join(CACHE_DIR, 'uglifyjs'),
            workers: true,
          },
```

Turning parallel off via `parallel: false` lets me build it. Setting `parellel:true` and `workers: false` also makes it work. Could it be an issue with the worker-farm?

**Comment by evilebottnawi** [comment] 2017-09-13 10:03
@kumarharsh @jinker known issue, should be fixed in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/108. Because `parallel` (workers) don't use as expected.

**Comment by WillooWisp** [comment] 2017-09-19 20:00
I experience similar issues with parallel enabled.

**Comment by evilebottnawi** [comment] 2017-09-19 20:39
@WillooWisp https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/118#issuecomment-329120704

**Comment by kumarharsh** [comment] 2017-09-20 07:18
@evilebottnawi great job on the PR. Quick question: does it address parallelization issue in Windows where the webpack process just hangs?

**Comment by evilebottnawi** [comment] 2017-09-20 10:39
@kumarharsh this PR should fix this, but need tests, can you test this PR on windows?

**Comment by kumarharsh** [comment] 2017-09-20 11:46
Unfortunately, seems like it gets stuck at the same place. The children spawned by worker-farm seem to not respond - no CPU is being used, and my build process is stuck at the uglify step. The Memory value also is static for a long time.

![image](https://user-images.githubusercontent.com/760112/30641931-6b27e99e-9e26-11e7-8de3-4d6a40c9fa1f.png)

**Comment by evilebottnawi** [comment] 2017-09-20 11:57
@kumarharsh can you create minimum reproducible test repo?

**Comment by michael-ciniawsky** [comment] 2017-10-21 03:19
We definitely need a repro repo here, there is a bug in somewhere either in the plugin or `worker-farm` on windows (7)

**Comment by evilebottnawi** [comment] 2017-10-25 10:46
@jinker friendly ping, can you try latest version?

**Comment by linh1987** [comment] 2017-10-27 07:05
just to chime in, We encountered the same issue with our CI environment:
Windows Server 2012 R2 / Teamcity
Node 6.4.0 with included NPM.

**Comment by jinker** [comment] 2017-10-29 07:49
OK, I will try later.

**Comment by vkrol** [comment] 2017-10-29 13:07
We have same problem with the following configuration:
Windows 10 1703
webpack 3.8.1
uglifyjs-webpack-plugin@1.0.1

**Comment by evilebottnawi** [comment] 2017-11-14 11:05
@jinker @vkrol @jinker can you create minimum reproducible test repo?

**Comment by brentwilton** [comment] 2017-11-22 02:44
We have been encountering the same issue on Windows 10.

With parallel turned on the dist/uglify/worker.js will successfully minify the file and process.send() the reply back to the parent, but the parent never receives the message from the forked process.

forked.child.on('message', this.receive.bind(this)) is never invoked in worker-farm/lib/farm.js even though the message is sent from the child fork.

It appears as if the IPC is not working between the child and parent processes. This may be due to Windows not handling large amounts of IPC traffic correctly.

However if I add the maxConcurrentCallsPerWorker: 1 option when creating the worker farm in dist/uglify/index.js then it appears to complete successfully.

```
this.workers = (0, _workerFarm2.default)({
  maxConcurrentWorkers: this.maxConcurrentWorkers,
  maxConcurrentCallsPerWorker: 1
}, workerFile);
```

Adding maxConcurrentCallsPerWorker: 1 prevents the parent from sending multiple requests via IPC before the child has responded.

If you are experiencing this issue can you try adding maxConcurrentCallsPerWorker: 1 to your ./node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js and see if it fixes the issue for you ?

Windows 10 1511
webpack: 3.8.1
uglifyjs-webpack-plugin: 1.1.0
nodejs 8.9.0

**Comment by michael-ciniawsky** [comment] 2017-11-22 03:15
@brentwilton Feel free to open a PR with this change for further discussion

**Closed** 2017-11-23 12:02 UTC
Labels: flag: Has pull request, priority: 2 (urgent), severity: 2 (regression), status: Needs repro, type: Bug

**Comment by michael-ciniawsky** [comment] 2017-11-23 21:46
Released in `v1.1.0` please test

**Comment by whitecolor** [comment] 2017-12-08 19:00
Using `1.1.2` I have this issue in windows 10 (WSL).

**Comment by StalkAlex** [comment] 2018-03-03 09:17
In last version everything works the same means not working with parallel option, so this issue should be reopened at least.  I'm using it on BashOnWindows Windows 10, but everything works if I run it as normal windows process.

**Comment by StalkAlex** [comment] 2018-03-03 09:24
This is [check](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/173/commits/80d3706ea8e4079eb8dffaeda0b3ec759f77f947#diff-e7a96c2789a906d04cb672681ad35471R29) should be improved I think. As it will faild in Windows's Ubuntu, but it's still Windows.

**Comment by lednhatkhanh** [comment] 2018-04-25 09:37
This should be reopene, still facing this with webpack 4 and version 1.2.5

**Comment by evilebottnawi** [comment] 2018-04-25 09:47
@lednhatkhanh no, original issue was solved, feel free to open new issue with minimum reproducible test repo. Thanks!
