### ISSUE TITLE
Uncaught TypeError: Cannot set property 'lastEffect' of null

### ISSUE THREAD

**Issue by endbay** [webpack-contrib/uglifyjs-webpack-plugin#393] opened 2019-02-07 00:42 UTC
* Operating System: Mac OS/Debian 9
* Node Version: v11.6.0
* NPM Version: 6.7.0
* webpack Version: 4.29.2
* uglifyjs-webpack-plugin Version: 2.1.1

After upgrading React (to v16.8.1, from v16.7.0) and Webpack (to v4.29.2, from v4.28.4) to latest version: `npm run build` is no longer working. Building works without errors, but frontend crash with `Uncaught TypeError: Cannot set property 'lastEffect' of null`. 

Builds are worked before together with `uglifyjs-webpack-plugin`. And with latest version without `uglifyjs-webpack-plugin` as well.

**Comment by evilebottnawi** [comment] 2019-02-07 08:23
I think problem in `uglify-js`, better use `terser` plugin (https://github.com/webpack-contrib/terser-webpack-plugin), anyway can you create minimum reproducible test repo?

**Comment by endbay** [comment] 2019-02-07 09:05
I wish i could deliver a reproducable, but this happens on a 3.5mb big output file. Not sure, on which component this happening. After uglifyjs file in webpack config the code is no longer readable.

I just tested it with `terser` and this is working. I'll go with terser in future then, thanks for letting me know about this plugin.

**Comment by evilebottnawi** [comment] 2019-02-07 09:33
@endbay maybe you comment/uncomment `import` and `require` to detect problem code for creating issue in uglify

**Comment by endbay** [comment] 2019-02-07 09:56
Looks like the Webpack & React upgrades wasn't the issue. I figured out this came from latest `i18next-react` @v10.0.0 (https://github.com/i18next/react-i18next). But this v10.0.0 is only for latest React version.

**Comment by dcworldwide** [comment] 2019-02-20 14:04
@endbay I have the same stack. Upgrade react, i18n-next... broken. Is there a solution?

**Comment by evilebottnawi** [comment] 2019-02-20 14:10
@dcworldwide use `terser-webpack-plugin`

**Comment by dcworldwide** [comment] 2019-02-20 15:31
Thank you.

**Comment by theskillwithin** [comment] 2019-02-21 03:29
https://stackoverflow.com/questions/53348653/react-cannot-set-property-lasteffect-of-null

**Comment by ammanvedi** [comment] 2019-03-05 08:26
same issue i can see error comes from a line where a hook is called i.e. `useEffect(() => {`

are you recommending terser as a quick fix or are you indicating that this wont get fixed in this package ?

**Comment by evilebottnawi** [comment] 2019-03-05 09:33
@ammanvedi `uglify` looks like abandoned, so we recommend switch to `terser` plugin, webpack@4 and webpack@5 by default use `terser`. I close this issue, because we can't fix it on our side, sorry.
Solutions:
- Fix problem in `uglify` (feel free to send a PR to their repo)
- Switch on `terser-webpack-plugin`

Thanks!

**Closed by evilebottnawi** 2019-03-05 09:33 UTC
Labels: flag: Needs more info
