### ISSUE TITLE
SyntaxError: Cannot declare a let variable twice

### ISSUE THREAD

**Issue by eahlberg** [webpack-contrib/uglifyjs-webpack-plugin#92] opened 2017-07-26 11:54 UTC
I'm running OS X, node 7.4.0, and transpile my JS using babel preset ES2015. I got the following error when running `v0.4.6`:
```
ERROR in bundle.js from UglifyJs
Name expected [bundle.js:25358,6]
```

After upgrading to `v.1.0.0-beta.1` this error was fixed, but somehow, the following error appear on Safari:
```
SyntaxError: Cannot declare a let variable twice: 'e'.
```

Any clues to why this is?
Thanks!

**Comment by evilebottnawi** [comment] 2017-07-26 12:06
@eahlberg error can be located in `uglify-es`. Can your provide minimum reproducible test repo?

**Comment by michael-ciniawsky** [comment] 2017-07-26 12:19
There is/was a known scope bug in Safari (`v10.0.0`? I think), which version are you currently using ?

**Comment by eahlberg** [comment] 2017-07-26 12:29
Yes, I read about that bug somewhere. I'm using `v10.0.3`, but I want to target older versions as well.

The issue is kind of tangled in a big repo, I'll try to come up with a minimum test case!

**Comment by eahlberg** [comment] 2017-07-26 14:34
Easier said than done apparently 🙁

Didn't manage to construct a simple case, but the code in my bundle which throws the error looks as follows, if it's to any help:
```
}, function(t, e, n) {
    (function(e) {
        var n = null; // [Error] SyntaxError: Cannot declare a let variable twice: 'e'
```

@evilebottnawi hmm, maybe I haven't completely grokked this, but if this is a bug in `uglify-es`, does it mean that I'm not transpiling correctly since my bundle shouldn't contain ES6 stuff after the transpiling?

**Comment by evilebottnawi** [comment] 2017-07-26 15:00
@eahlberg beta version uglify plugin should be works with ES6. Do your use `babel-loader`? Maybe something in `babel` don't compile in right way. It is hard to debug this without test repo :disappointed: 
Who can don't work as expected:
1. `babel-loader` (maybe some plugin for babel don't work as expected)
2. `uglify-es` (maybe something don't compress in right way)
3. Bug in `safari` (can your test this in other browsers?)

**Comment by eahlberg** [comment] 2017-07-26 15:09
Yes, I use `babel-loader`. I'll try to upgrade the `babel` packages and see if it fixes the bug.

As for 3, it works fine in Firefox and Chrome.

**Comment by eahlberg** [comment] 2017-07-26 15:38
Unfortunately, upgrading the `babel` packages didn't fix the issue.

**Comment by evilebottnawi** [comment] 2017-07-26 15:41
@eahlberg can your step by step remove code from your code base to understand what code produces an error?

**Comment by eahlberg** [comment] 2017-07-27 10:25
I think I have pinned down the bug now. 

If I'm not totally wrong, the cause was in one of the libraries I use, specifically on [this](https://github.com/fantasyland/daggy/blob/master/src/daggy.js#L1) line (which shadows `toString`), in combination with mangling. I can't really see why that line would be incorrect, but since there's a confirmed bug in Safari concerning this, I guess that might have something to do with it. Do you have any idea about why that is? Anyway, If I turn off mangling using `{uglifyOptions: { mangle: false } }`, it works. I shouldn't have ignored the warning sign on the mangling option!

Hope this at least helps a bit. Thanks for your help!

**Comment by evilebottnawi** [comment] 2017-07-27 10:34
@eahlberg `mangle` is danger, but `const { toString } = require('sanctuary-type-classes')` should be work. Can your test code without `uglify` plugin and without `babe-loader`? Error happens only when uglify plugin enable?

**Comment by evilebottnawi** [comment] 2017-07-27 10:47
@eahlberg seems bug inside `uglify-es`, can your create issue in `uglify` repo with reference on this issue?

**Comment by michael-ciniawsky** [comment] 2017-07-27 11:29
Mangling can be destructive in certain cases, it is 'advanced' usage and a 'non-safe' transformation, closing since it is unrelated to `uglifyjs-webpack-plugin` itself :)

**Closed by michael-ciniawsky** 2017-07-27 11:29 UTC
Labels: flag: Needs more info

**Comment by kzc** [comment] 2017-08-25 04:03
> SyntaxError: Cannot declare a let variable twice

This is an ES6 bug in Safari 10:

https://bugs.webkit.org/show_bug.cgi?id=171041

To workaround this Safari 10 bug set the `uglify-es` `mangle` option `safari10`:

> ## Mangle options
> 
> - `safari10` (default `false`). Pass `true` to work around the Safari 10 loop
  iterator [bug](https://bugs.webkit.org/show_bug.cgi?id=171041) "Cannot declare a let variable twice".

related links: 

https://github.com/mishoo/UglifyJS2/tree/harmony#mangle-options
https://github.com/mishoo/UglifyJS2/issues/1753
https://github.com/mishoo/UglifyJS2/pull/1851

**Comment by olafahn** [comment] 2017-09-23 03:59
But `mangle: true` option cannot eliminate the Error (**SyntaxError: Cannot declare a let variable twice**).
I installed `"uglifyjs-webpack-plugin": "^1.0.0-beta.2",`
and the below is my UglifyJS option
```javascript
var UglifyJsPlugin = require('uglifyjs-webpack-plugin');

// ...
  new UglifyJsPlugin({
    sourceMap: true,
    parallel: {
      cache: true,
    },
    uglifyOptions: {
      ie8: false,
      ecma: 5,
      warnings: false,
      compress: true,
      mangle: {
        safari10: true,
      },
      output: {
        comments: false,
      },
    },
  }),
```

**Comment by olafahn** [comment] 2017-09-23 04:43
If there is someone who suffering with same problem like me,
try babel-minify-webpack-plugin instead. Everything works fine right now.

**Comment by kzc** [comment] 2017-09-23 13:58
You probably had a configuration issue. We'll never know without a standalone minimal reproduction.

Using `uglify-es` directly on the example from the [Safari 10 WebKit bug report](https://bugs.webkit.org/show_bug.cgi?id=171041):
```
$ cat safari10_bug.js 
let e = e => {
    console.log(e);
    for (let e of [1, 2, 3]) // Cannot declare a let variable twice: 'e'.
        console.log(e);
};
```
```
$ bin/uglifyjs -V
uglify-es 3.1.1
```
```
$ bin/uglifyjs safari10_bug.js -m -b
let e = o => {
    console.log(o);
    for (let o of [ 1, 2, 3 ]) console.log(o);
};
```
``` 
$ bin/uglifyjs safari10_bug.js -m safari10=true -b
let e = o => {
    console.log(o);
    for (let l of [ 1, 2, 3 ]) console.log(l);
};
```

**Comment by olafahn** [comment] 2017-09-24 18:59
@kzc I don't know why, but suddenly all seems working well.
Thanks for your consideration, kzc.
Indeed, babel-minify was too slow, and consumes memory too much.

**Comment by antonlitvinenko** [comment] 2017-12-02 01:30
@olafahn Hi! do you have any idea what in the end caused this issue? Seems like we are having the same issue and the only way to workaround it so far was to turn off the mangle.

Thanks!

**Comment by olafahn** [comment] 2018-01-04 02:29
@antonlitvinenko Hello!
I just guess that some webpack configuration issue,
especially, webpack version issue. I suggest you to checkout to new branch, then update some of babel related packages first, i think that solved me in my case.
Hope this work!

**Comment by kzc** [comment] 2018-01-04 03:56
The solution has been repeated several times. It's not magic.

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/92#issuecomment-331637609

https://github.com/mishoo/UglifyJS2/issues/1753#issuecomment-324814782

**Comment by jesalg** [comment] 2018-01-26 20:36
Similar to @olafahn, I have `"uglifyjs-webpack-plugin": "^1.1.6",` installed with this in my webpack config:

```
new UglifyJsPlugin({
      sourceMap: true,
      uglifyOptions: {
        ecma:8,
        mangle: {
          safari10: true
        }
      }
    }),
```
Despite that I'm still seeing `SyntaxError: Cannot declare a let variable twice` in Safari 10.x. Could it be that `safari10` flag is not being passed onto UglifyJS2? I don't see that being listed under the [supported mangle properties](https://github.com/mishoo/UglifyJS2/tree/harmony#mangle-properties-options).

**Comment by kzc** [comment] 2018-01-26 20:58
>  I don't see that being listed under the supported mangle properties.

Because it's not in the mangle properties section. Search for "safari10" in the docs.

**Comment by jesalg** [comment] 2018-01-26 21:07
@kzc Thanks yeah I see it now. 

Anyway, I must not have cleared my cache. It seems to be working now on Safari 10!

**Comment by dtmp** [comment] 2018-09-19 17:01
Add uglifyOptions like this:


```
import {createWebpackConfig} from 'haul';

...

export default {
    webpack: env => {
        const config = createWebpackConfig({
            entry: './src/index.ts',
        })(env);
        
        ...

        if (config.optimization && config.optimization.minimize) {
            config.optimization.minimizer[0].options.uglifyOptions.mangle = {safari10: true};
        }

        return config;
    }
};
```
